eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: registration-service
  data:
    mongodb:
      uri: mongodb://localhost/userregistration
