rails_frontend:
  image: gruntwork/rails-frontend
  volumes:
    - ./rails-frontend:/usr/src/app
  ports:
    - "3000:3000"
  environment:
    - RAILS_ENV=development
  links:
    - sinatra_backend

sinatra_backend:
  image: gruntwork/sinatra-backend
  volumes:
    - ./sinatra-backend:/usr/src/app
  ports:
    - "4567:4567"
  environment:
    - RACK_ENV=development